export const CHANGE_SELECTED_KEYWORD = 'CHANGE_SELECTED_KEYWORD';
export const CHANGE_SELECTED_ENTRY = 'CHANGE_SELECTED_ENTRY';
export const CHANGE_SELECTED_FORM = 'CHANGE_SELECTED_FORM';
export const SHOW_HOME_DASHBOARD = 'SHOW_HOME_DASHBOARD';
